# <span style="color:orange">Atomic Spectroscopy</span>
Project-based laboratory exercise in the course Atomic and Molecular Physics (FYSB24)
### Names: Oscar Emil Strickland, Robin Svegin
## Table of Content
 [Introduction](#Introduction)
* [1.The spectrum of Hydrogen](#Hydrogen)
  * [1.1 Open the spectrum](#Hydrogen_Step_1)
  * [1.2 Gaussian fit](#Hydrogen_Step_2)
  * [1.3 Calculate Rydberg constant](#Hydrogen_Step_3)
  * [1.4 Discussion](#Hydrogen_Step_4)
* [2.The quantum defect](#quantum_defect)
  * [2.1 Open the Na spectrum](#quantum_1)  
  * [2.2 Open a saturated spectrum](#quantum_2) 
  * [2.3 Calculate experimental values for the quantum defect](#quantum_3) 
  * [2.4 Calculate the vacuum wavelength for the 3p – 8d transition](#quantum_4)  
  * [2.4 Discussion](#quantum_5)  
* [3.Fine structure](#fine_structure)  
  * [3.1 Open file and identify peaks](#fine_structure_1)  
  * [3.2 Conduct the analysis](#fine_structure_2)    
  * [3.2 Discussion](#fine_structure_3)
--------------------------------------------------------------------------------------------------------------

## Introduction <a name="Introduction"></a>
This Jupyter Notebook is meant to conduct the anaylsis as well as to present the results of the atomic spectroscopy lab. Generally all code provided is a guideline in order to get your analysis started. In case you want to use your own methods, feel free to change as much of the code as  you like. Each of the three tasks starts with the analysis of the data, followed by some calculations and ends with a discussion. The first task provides a lot of the code needed, whereas in the last part most of the coding is up to you. 
<br>

**Before you can run any part, you need to import the modules below (shift + enter):**



In [2]:
# Packages to access files in the system
import sys, os

# Package that supports mathmatical operations on arrays
import numpy as np  

# Package that supports operations for data structures and numeric tables
import pandas as pd

# Package for plotting; 
# first line makes plots interactive, 
# second actually loads the library
%matplotlib notebook
import matplotlib.pyplot as plt

# Function that fits a curve to data 
from scipy.optimize import curve_fit

sys.path.append('./lib')
import fittingFunctions

--------------------------------------------------------------------------------------------------------------

# <span style="color:orange">1. The spectrum of Hydrogen</span> <a name="Hydrogen"></a>
## 1.1 The spectrum of Hydrogen<a name="Hydrogen_Step_1"></a>
Record a spectrum of the hydrogen lamp using the spectrometer channel with large range. Make sure the measurement is strong, but not saturated. Save the data as ASCII file and transfer them to the computer on which you have your Jupyter Notebook. With the function  `read ` from package  `pandas ` one loads in the experimental data. To do this, you have to specify the data path and file name accordinlgy in the field below. Please mind that the **absolute path** must be specified using `/` instead of `\`.

In [4]:
# Specify the absolute path for the hydrogen spectrum inside quotation marks:
df = pd.read_csv("/workspaces/Atomic-Spectroscopy-FYSB24/Measurements/30-1-Hydrogen_1804346U2.txt", 
    sep=";",    # Here we specify that values are seperated by semicolons.
    header=6,   # This skips the first rows of the file containing information about the acquisiton settings
                 
    # Check if your spectrum txt file contains of 4 or 5 coulumns. If you have 5 coulumns use the adapted 'names'-array the line below.        
    # names=["Wavelength", "Count sample", "Background", "Reference"])
     names=["Wavelength", "Count sample", "Background", "Reference", "Corrected for dark"])

df = df.stack().str.replace(',','.').unstack() # Turns the  ',' in the data frame to a point
data = df.to_numpy() #Converts the data frame into an Numpy array
wavelength = np.array(list(data[:, 0]), dtype=float) # Turns the Numpy 2d array with the wavelengths in a regular 2D float array
counts = np.array(list(data[:, 4]), dtype=float) # If you have saved 5 coulumns, use the 'Corrected for dark values' by changing the '1' to a '4'.

plt.figure()
plt.plot(wavelength, counts)
plt.show()
plt.title("Hydrogen")      # set title of the plot
plt.xlabel("Wavelength")   # set label for x-axis 
plt.ylabel("Counts")       # set label for Y-axis 
plt.savefig("hydrogen.png")

<IPython.core.display.Javascript object>

## 1.2 Gaussian fit<a name="Hydrogen_Step_2"></a>
Perform a Gaussian fit on the peaks in order to exactly determine the position of the peaks. You have to specify the region in which the Gaussian fit shall be performed. Adapt the other parameters (mu_guess, A_guess and sigma_guess) to successfuly run the fit. 

In [5]:
peak1 = fittingFunctions.perform_Gaussian_fit(x=wavelength, 
                                              y=counts,      
                                              region_start=650,   # bins where to start fitting
                                              region_stop=660, # bins where to stop fitting
                                              mu_guess=656,       # guess for the position of peak centroid
                                              A_guess=20000,       # guess for the amplitude of the peak
                                              sigma_guess=10)      # guess for the sigma

<IPython.core.display.Javascript object>

Estimated parameters:
 A = 18714.96143, mu = 656.26989,  sigma = 0.13080 

Uncertainties in the estimated parameters: 
 σ²(A) = 39107.66239, σ²(mu) = 0.00000, σ²(sigma) = 0.00000 

Covariance matrix: 
 [[ 3.91076624e+04  1.68104485e-03  1.68411831e-01]
 [ 1.68104485e-03  2.76425245e-06 -9.34876871e-08]
 [ 1.68411831e-01 -9.34876871e-08  2.42901381e-06]]


  * Extract the peak position `mu`. Repeat the fit for as many peaks that you are able to find. Insert the wavelength in the table below. Adapt the table length if you find more than five lines in the spectrum.  <br> 
  *  Identify the lines of the Balmer series using the NIST data base and assign them the correspoding transition. <br> 
  * Convert your values to vacuum wavelength. 

In [9]:
# Insert the extracted wavelength here. You can add/or remove rows from the table.
hydrogen_wavelength = ([434.07980, 486.14420 , 656.26989, 842.23174])
# Compare the number with the nist database and identify the transition.
hydrogen_transistions=(["5 to 2", "4 to 2", "3 to 2","19 to 3"])

# Write a formula converting the values from the table above to vacuum wavelength.
hydrogen_vac_wavelength = ([None , None, None , None])

for i in range(len(hydrogen_wavelength)):
    hydrogen_vac_wavelength[i] = 1.000293*hydrogen_wavelength[i]

# Nothing to change below here:
pd.DataFrame([hydrogen_transistions, hydrogen_vac_wavelength], columns=['1', '2', '3','4'], index=['Transition', 'Vacuum wavelength'])

1          2           3           4
Transition             5 to 2     4 to 2      3 to 2     19 to 3
Vacuum wavelength  434.206985  486.28664  656.462177  842.478514

## 1.3 Calculate Rydberg constant<a name="Hydrogen_Step_3"></a>


Use your extracted data to determine an experimental value for the [Rydberg constant](https://en.wikipedia.org/wiki/Rydberg_constant) of hydrogen using the formula from the course book:
<br>
$  h \nu = \frac{h c}{\lambda}= R_{H}\left(\frac{1}{n_{1}^{2}}-\frac{1}{n_{2}^{2}}\right)$,
<br>
where  $n_{1}$ and $n_{2}$ are two consecutive quantum numbers. Use the empty code box below to write your own code to extract the Rydberg constant.

In [15]:
upper_levels=[5,4,3,19]
lower_levels=[2,2,2,3]
wavelength_meters=np.array(hydrogen_vac_wavelength)*10**(-9)
rydberg=[]
for i in range(len(upper_levels)):
    rb=(1/wavelength_meters[i])/((1/lower_levels[i]**2)-(1/upper_levels[i]**2))
    rydberg.append(rb)

print("Computed Rydberg:", sum(rydberg)/len(rydberg))
print("Literature Rydberg: 10 973 731.6")

Computed Rydberg: 10964538.777263438
Literature Rydberg: 10 973 731.6


## 1.4 Discussion <a name="Hydrogen_Step_4"></a>
Describe below the procedure (spectrometer settings) used for the experimental determination of result and any difficulties with the measurement, or how to overcome them. Compare the experimental value for the Rydberg constant with literature in a brief text. Perform an error estimation and discuss whether your result is reasonable.

Using the spectrometer with an integration time of 25ms and and average over 15 scans the data was collected. Using the provided fitting functions the peaks were identified, and comparing this to the NIST database the prinicipal quantum numbers were found. These values were then plugged into the Rydberg formula, the Rydberg constant was computed and the average was taken across all found transitions. Comparing the computed value to the value found in literature, we see that our value for the Rydberg constant is 99.9% of the accepted value, which is very close, so the result is reasonable.  

--------------------------------------------------------------------------------------------------------------
# <span style="color:orange">2. The quantum defect</span> <a name="quantum_defect"></a>
Plug in the sodium lamp in the lamp holder and measure a spectrum using the spectrometer channel with large range. 
Since sodium has a very intense feature, you need to record two spectra with different integration time. The unsaturated spectrum gives the wavelength of the intense line. The saturated spectrum (with the strong line being cut-off) will reveal the less intense features. Focus on the region between 430 and 630 nm when adjusting the intensity, ignoring the strong feature.

## 2.1 Open the full, unsaturated sodium spectrum <a name="quantum_1"></a>
Load in the spectrum that is not saturated (the strong feature not being cut off).

In [ ]:
# Specify the absolute path for the unsaturated sodium spectrum inside quotation marks:
df = pd.read_csv("/workspaces/Atomic-Spectroscopy-FYSB24/Measurements/30-1-SodiumHi.txt", 
    sep=";",    # Here we specify that values are seperated by semicolons.
    header=6,   # This skips the first rows of the file containing information about the acquisiton settings   

    # Check if your spectrum txt file contains of 4 or 5 coulumns. If you have 4 coulumns use the adapted 'names'-array the line below.        
    # names=["Wavelength", "Count sample", "Background", "Reference"])
    names=["Wavelength", "Count sample", "Background", "Reference", "Corrected for dark"])

df = df.stack().str.replace(',','.').unstack() # Turns the  ',' in the data frame to a point
data = df.to_numpy() #Converts the data frame into an Numpy array
wavelength = np.array(list(data[:, 0]), dtype=float) #Turns the Numpy 2d array in a regular 2D float array
counts = np.array(list(data[:, 1]), dtype=float) # If you have saved 5 coulumns, use the 'Corrected for dark values' by changing the '1' to a '4'.
plt.figure()
plt.plot(wavelength, counts)
plt.show()
plt.title("Sodium unsaturated")      # set title of the plot
plt.xlabel("Wavelength")   # set label for x-axis 
plt.xlim(430, 630)         # set range for x-axis
plt.ylabel("Counts")       # set label for Y-axis 

FileNotFoundError: [Errno 2] No such file or directory: 'C:/ExampleFolder/ExampleFolder/Sodium_unsaturated.txt'

Analogue to the previous part, perform a Gaussian fit on the peaks in order to exactly determine the peak position.

In [ ]:
peak1 = fittingFunctions.perform_Gaussian_fit(x=wavelength, 
                                              y=counts,      
                                              region_start=580,   # bins where to start fitting
                                              region_stop=600,    # bins where to stop fitting
                                              mu_guess=585,       # guess for the position of peak centroid
                                              A_guess=60000,       # guess for the amplitude of the peak
                                              sigma_guess=1)      # guess for the sigma

Extract the wavelength of all transitions for which n = 3 is the lower energy level. Enter your result in the table provided further down under section [2.3](#quantum_3). 

## 2.2 Open a saturated spectrum <a name="quantum_2"></a>
Load in the saturated spectrum at which you adjusted the intensity in the range between 430 nm and 630 nm, saturating the strong feature that had been determined before by the unsaturated measurement. Perform Gaussian fits in order to exactly determine the peak positions.

In [ ]:
# Specify the absolute path for the saturated sodium spectrum inside quotation marks:
df = pd.read_csv("C:/ExampleFolder/ExampleFolder/Sodium_saturated.txt", 
    sep=";",    # Here we specify that values are seperated by semicolons.
    header=6,   # This skips the first rows of the file containing information about the acquisiton settings

    # Check if your spectrum txt file contains of 4 or 5 coulumns. If you have 4 coulumns use the adapted 'names'-array the line below.        
    # names=["Wavelength", "Count sample", "Background", "Reference"])
    names=["Wavelength", "Count sample", "Background", "Reference", "Corrected for dark"])                 
                 
df = df.stack().str.replace(',','.').unstack() # Turns the  ',' in the data frame to a point
data = df.to_numpy() #Converts the data frame into an Numpy array
wavelength = np.array(list(data[:, 0]), dtype=float) #Turns the Numpy 2d array in a regular 2D float array
counts = np.array(list(data[:, 1]), dtype=float) # If you have saved 5 coulumns, use the 'Corrected for dark values' by changing the '1' to a '4'.

plt.figure()
plt.plot(wavelength, counts)
plt.show()
plt.title("Sodium saturated")      # set title of the plot
plt.xlabel("Wavelength")   # set label for x-axis 
plt.xlim(430, 630)         # set range for x-axis
plt.ylabel("Counts")       # set label for Y-axis 

In [ ]:
peak1 = fittingFunctions.perform_Gaussian_fit(x=wavelength, 
                                              y=counts,      
                                              region_start=610,   # bins where to start fitting
                                              region_stop=620,    # bins where to stop fitting
                                              mu_guess=615,       # guess for the position of peak centroid
                                              A_guess=6000,       # guess for the amplitude of the peak
                                              sigma_guess=1)      # guess for the sigma

Identify all the small peaks, which are otherwise hidden in the noise. Again try to find as many transitions for which n = 3 is the lower energy level and enter the values in the table below, section [2.3](#quantum_3).

## 2.3 Calculate experimental values for the quantum defect <a name="quantum_3"></a>
Intentify the transistion, with n=3 is the lower energy level, using the [NIST data base](https://physics.nist.gov/PhysRefData/ASD/lines_form.html).

In [ ]:
### Enter your results in the arrays below. You can add/or remove rows from the table.
sodium_wavelength = ([None , None, None , None, None])
sodium_upperlevel=(["Empty", "Empty", "Empty", "Empty", "Empty"])
sodium_lowerlevel=(["Empty", "Empty", "Empty", "Empty", "Empty"])

# -> TODO <- write a formula converting the values from the table above to vacuum wavelength.
sodium_vac_wavelength = ([None , None, None , None, None])

pd.DataFrame([sodium_vac_wavelength, sodium_upperlevel, sodium_lowerlevel], columns=['1', '2', '3','4', '5'], index=['Vacuum wavelength / nm','Upper level','Lower level'])

1      2      3      4      5
Vacuum wavelength / nm   None   None   None   None   None
Upper level             Empty  Empty  Empty  Empty  Empty
Lower level             Empty  Empty  Empty  Empty  Empty

*  Use the field below to develop your own code to calculate the experimental values for the quantum defect $\delta{(l)}$. of all involved energy levels. For this, use the tabulated value for the first ionization energy of sodium.  Take the values over into the result table below. 
* Find literature values for the constants and write them in the table.

More information can be found in your textbook.

In [ ]:
### Write your code here

In [ ]:
### Enter your results in the result table below:
Quantum_defect_exp = ([None , None, None , None, None])
Quantum_defect_lit = ([None , None, None , None, None])

pd.DataFrame([sodium_wavelength, sodium_upperlevel, sodium_lowerlevel, Quantum_defect_exp, Quantum_defect_lit], columns=['1', '2', '3','4', '5'], index=['Wavelength / nm','Upper level','Lower level','Calculated quantum defect','Literature quantum defect'])

## 2.4 Calculate the vacuum wavelength for the 3p – 8d transition <a name="quantum_4"></a>
Estimate the vacuum wavelength for the transition 3p – 8d in sodium as accurately as possible.
Enter the formula that you use here (you can write LaTex code):

$Replace\;this\;with\;your\;equation.$

Use the empty code box below to write your own code to calculate the vacuum wavelength:

In [ ]:
### Write your code here.

## 2.5 Discussion <a name="quantum_5"></a>
Describe your procedure (particularly the spectrometer settings) and discuss your results for the quantum defects and the 3p-8d vacuum wavelength in the field below. Compare your result with literature values and do an error estimation. Comment, in particular, on the internal order of the energy levels corresponding to different orbitals, and on the underlying physics. 
Include a (hand- or computer) drawing of the energy level diagram of sodium containing the lines that have been observed (Edit > Insert image). Also indicate the measured wavelength of each transition in the drawing.

Double-click to discuss your results here.

--------------------------------------------------------------------------------------------------------------
# <span style="color:orange">3. Fine structure</span> <a name="fine_structure"></a>
## 3.1 Open file and identify peaks <a name="fine_structure_1"></a>
Plug in the cadmium lamp in the lamp holder and measure a spectrum using the spectrometer **channel** with **small range**, but **high resolution**. Focus on the region **between 340 and 362 nm** when adjusting the **intensity**. In this last part you are supposed to conduct more of the analysis on your own. Try to modify the code in order to extract peak height and position.

In [14]:
# Specify the absolute path for the cadmium spectrum inside quotation marks:
df = pd.read_csv("/workspaces/Atomic-Spectroscopy-FYSB24/NewCadmium2.txt", 
    sep=";",    # Here we specify that values are seperated by semicolons.
    header=6,   # This skips the first rows of the file containing information about the acquisiton settings
                 
    # Check if your spectrum txt file contains of 4 or 5 coulumns. If you have 4 coulumns use the adapted 'names'-array the line below.        
    # names=["Wavelength", "Count sample", "Background", "Reference"])
    names=["Wavelength", "Count sample", "Background", "Reference", "Corrected for dark"])  

df = df.stack().str.replace(',','.').unstack() # Turns the  ',' in the data frame to a point
data = df.to_numpy() #Converts the data frame into an Numpy array
wavelength = np.array(list(data[:, 0]), dtype=float) #Turns the Numpy 2d array in a regular 2D float array
counts = np.array(list(data[:, 4]), dtype=float) # If you have saved 5 coulumns, use the 'Corrected for dark values' by changing the '1' to a '4'.

plt.figure()
plt.plot(wavelength, counts)
plt.show()
plt.title("Cadmium")       # set title of the plot
plt.xlabel("Wavelength")   # set label for x-axis
plt.xlim(338, 362)         # set range for x-axis
plt.ylim(-100,10000)
plt.ylabel("Counts")       # set label for Y-axis 
plt.savefig("cadmium_new2.png")

<IPython.core.display.Javascript object>

In [69]:
peak1 = fittingFunctions.perform_Gaussian_fit(x=wavelength, 
                                              y=counts,      
                                              region_start=360,   # bins where to start fitting
                                              region_stop=361,    # bins where to stop fitting
                                              mu_guess=360.49,       # guess for the position of peak centroid
                                              A_guess=250,       # guess for the amplitude of the peak
                                              sigma_guess=0.01)      # guess for the sigma

<IPython.core.display.Javascript object>

Estimated parameters:
 A = 839.38137, mu = 360.48893,  sigma = 0.00400 

Uncertainties in the estimated parameters: 
 σ²(A) = 294560341585159.56250, σ²(mu) = 68.60276, σ²(sigma) = 231.59690 

Covariance matrix: 
 [[ 2.94560342e+14  1.42151904e+08 -2.61187988e+08]
 [ 1.42151904e+08  6.86027568e+01 -1.26046175e+02]
 [-2.61187988e+08 -1.26046175e+02  2.31596897e+02]]


* Determine the vacuum wavelengths of as many lines as possible in the wavelength range 340-362 nm of your collected spectra.
* Identify the cadmium transitions corresponding to the different spectral lines and make sure that you find a multiplet with in total six transitions.
* Determine the relative energies of the fine structure levels of the two involved triplets.

Create a table for all the identified spectral lines including the vacuum wavelengths and the energy levels involved in the transitions

In [75]:
### Write your results here.
Cadmium_wavelength = ([340.01548 ,346.54722 ,346.68871 ,360.15454 , 360.30415,360.48893])
#last wavelength is a bit low intensity on the plot, but looking in the text file we see the peak still 
#and the gaussian can clearly find it 
next_row = (["^3P_0 to ^3D_1" , "^3P_1 to ^3D_2", "^3P_1 to ^3D_1" , "^3P_2 to ^3D_3", "^3P_2 to ^3D_2","^3P_2 to ^3D_1"])
Cadmium_vac_wavelength=[]
for i in range(len(Cadmium_wavelength)):
    vaclength=Cadmium_wavelength[i]*1.000293
    Cadmium_vac_wavelength.append(vaclength)

pd.DataFrame([Cadmium_vac_wavelength, next_row], columns=['1', '2', '3','4', '5','6'], index=['Wavelength / nm','Transition'])

1               2               3  \
Wavelength / nm      340.115105      346.648758       346.79029   
Transition       ^3P_0 to ^3D_1  ^3P_1 to ^3D_2  ^3P_1 to ^3D_1   

                              4               5               6  
Wavelength / nm      360.260065      360.409719      360.594553  
Transition       ^3P_2 to ^3D_3  ^3P_2 to ^3D_2  ^3P_2 to ^3D_1

## 3.2 Conduct the analysis <a name="fine_structure_2"></a>
Check whether the fine structure of the studied terms in agreement with the Landé interval rule. If not, what is a possible reason for this? Use the empty code box below to write your own code. 

In [ ]:
#first we need to convert wavelengths to energy 

energies = [1.0 / (wl * 1e-7) for wl in Cadmium_vac_wavelength]

#we check if the gap in energy is proportional to the change in J

#  upper triplet (5s5d ^3D)
# We use transitions from the same lower level (P2) to find the D-splittings.
# Gap 3-2: E(P2 -> D3) - E(P2 -> D2)
gap_D_32 = energies[3] - energies[4]

# Gap 2-1: E(P2 -> D2) - E(P2 -> D1)
gap_D_21 = energies[4] - energies[5]

ratio_D = gap_D_21 / gap_D_32 #woops divided wrong way round before 

# lower triplet (5s5p ^3P)
# now usr same upper level (D1) to find P-splittings.
# Gap 2-1: E(P1 -> D1) - E(P2 -> D1) = (D1 - P1) - (D1 - P2) = P2 - P1
gap_P_21 = energies[2] - energies[5]

# Gap 1-0: E(P0 -> D1) - E(P1 -> D1) = (D1 - P0) - (D1 - P1) = P1 - P0
gap_P_10 = energies[0] - energies[2]

ratio_P = gap_P_21 / gap_P_10

# 5. Output Results
print("--- Landé Interval Rule Results ---")
print(f"Upper Triplet (D) Ratio: {ratio_D:.3f}")
print(f"  Theoretical: 1.5 (3/2)")


print(f"Lower Triplet (P) Ratio: {ratio_P:.3f}")
print(f"  Theoretical: 2 (2/1)")


--- Landé Interval Rule Results ---
Upper Triplet (D) Ratio: 1.234
  Theoretical: 1.500 (3/2)
Lower Triplet (P) Ratio: 1.951
  Theoretical: 2.000 (2/1)


## 3.3 Discussion<a name="fine_structure_3"></a>
Describe your procedure and discuss your results in field below. Compare your result with literature values and do an error estimation. Furthermore, answer the following points:

* Include a drawing (by hand or computer) of the energy level diagram of cadmium containing the observed transitions (Edit > Insert image).
* There is a hardly visible line around 350 nm. To what energy levels does this transition correspond to? Why is it so weak, and why can we see it at all?

## 3.4 Procedure<a name="fine_structure_3"></a>
We use the vacuum wavelengths to calculate the energies in $cm^{-1}$. We then identify which transitions in the fine structure begin or end at the same level and compare the energies of these differences which is the fine structure energy. The Landé interval rule says the gaps in the fine structure are proportional to the change in the total angular momentum J. As we know the J for each level, we simply divide the energy differences and see if the ratio matches the ratio in J.  

## 3.5 Discussion<a name="fine_structure_3"></a>
Computing the equivalent ratios from NIST data, we get the ratios 1.498 and 2.16, which differ significantly from the ratios computed from the data. We have an error of 18% for the upper triplet and 10% for the lower triplet. Both ratios are lower than the ones calculated from NIST. This is most likely due to the fact that the measured wavelengths are consistently lower than the wavelengths reported by NIST, which will shift the ratio down as the ratio for J is fixed.   

The line we see at 350nm corresponds to $4d^{10}5s5p ^1D_2$ to  $4d^{10}5s5p ^3P_1$ so we change from a singlet to a triplet state. In normal LS-coupling we have the selection rule $\Delta S\neq 0$ (the spin doesn't change under electron transition). This transition is forbidden under full LS-coupling, but as Cadmium is relatively heavy, the spin-orbit coupling is becomes stronger and causes the triplet state to overlap slightly with the singlet state, which allows the transition to occur. This effect is more noticable in heavier atoms, as the spin-orbit coupling is proportional to the atomic mass, but this effect starts to become visible around the mass of Cadmium, even if the intensity is very small. 